### ISSUE TITLE
release 0.2.1 reporting itself as version 3.0

### ISSUE THREAD

**Issue by lsh-0** [3sd/civicrm-inky-compose#1]
not sure if it's important, I'm no expert here, but after upgrading from 0.1.0 to 0.2.1, civi is reporting version 3.0 is installed, probably from this file: https://github.com/3sd/civicrm-inky-compose/blob/master/info.xml#L18

**Comment by michaelmcandrew** [comment]
Thanks, it was a minor issue but potentially confusing. I fixed it in https://github.com/3sd/civicrm-inky-compose/releases/tag/0.2.2
